### PR TITLE
Rotate cards 90 deg

### PR DESCRIPTION
**Pull request by Hanaffi**

### CODE REVIEW

**Comment by Hanaffi** [comment]
@ekzhang @cynthiakedu Can someone review it?

**Comment by ekzhang** [comment]
Thanks! We'll look at this soon.

**Comment by ekzhang** [comment]
Hi @Hanaffi, thanks for the contribution. The spacing here is not correct; the cards should fill up the board and only have a small amount of padding between each other, as in the current layout. This allows the cards to be larger.

image

Your code is also producing several hundred warnings in the console.

image

**Comment by Hanaffi** [comment]
@ekzhang I'll fix that.

**Comment by ekzhang** [comment]
New layout after some math / geometry

image

**Review by ekzhang — APPROVED** [review]

**Comment by ekzhang** [comment]
Thanks @Hanaffi for taking initiative on this!

**Pull request merged**
