### PR TITLE
Filter stats for game types

### PR DESCRIPTION
**Pull request by wenley**
### Context

I play many many solo games to practice, and only occasionally play
games with other people. When looking at my stats, I'd like to see how I
do playing with others separately from my performance alone.

Very open to suggestions about implementation choices! I went with what
made sense to me, but I can't help but wonder if there's a clearer way
to write the `keys().filter().reduce()` chain.

Originally suggested in Discord: [Link](https://discordapp.com/channels/718326911583125544/718457117756883045/737094564959092756)

### Open Questions

- The term "game set" is unclear even to me. What's the clearest term to use?
- UI Design: I went with the easiest default layout, but I don't like
how it looks. I tried in-lining the select with the "Statistics" title,
but it looked totally wonky with default CSS.

### Screenshots

**Implemented Layout**
image

**Inline Layout**
image

### CODE REVIEW

**Comment by ekzhang** [comment]
Hi @wenley, this looks great! Thanks for contributing this feature, it seems really useful. A couple comments:

1. Can you run your code through [Prettier](https://prettier.io/)?
2. What does your code do when `gamesData` is `null`? Can you check that there's no errors in the console on first page load? I feel like `Object.keys(null)` could potentially cause an error.
3. Since you asked about your reduce implementation: it seems correct, but you could simplify this by just changing the condition on line 89 to something like `if (gameVals[i].status === "done" && GAME_SUBSET...[...](gameVals[i]))`. What do you think? Alternatively, it might actually work better to do the filtering in the `UserStatistics` component.

Re: design, maybe the label "Variant" instead of "Game Set"? As for the layout, I totally relate to not being able to figure out where to put things on the page. Just brainstorming here, but maybe it'd make sense to implement some kind of dropdown menu that's positioned in the top-right of the UserStatistics component.

**Comment by wenley** [comment]
> Prettier

@ekzhang Done!

> when `gamesData` is `null`?

Surprisingly, at least locally, there was no error. Maybe something about the local testing version of the app never taking time to load data between https://github.com/ekzhang/setwithfriends/blob/8b60fa1f7bc8d8ea7d37dc91eccdadcba6b9a9b6/src/pages/ProfilePage.js#L67-L69 and https://github.com/ekzhang/setwithfriends/blob/8b60fa1f7bc8d8ea7d37dc91eccdadcba6b9a9b6/src/pages/ProfilePage.js#L72 ? Fixed as suggested since I agree with your prediction about `Object.keys(null)`.

> simplify

Ah, indeed! Good call. I'm gonna leave it outside `UserStatistics` for now, but a behavior change from my original implementation: Given the placement of the dropdown, I'm now also applying the filter to the data for the table below. That makes it all consistent. If we'd rather only apply the filter to the stats view, I think that's a good motivation to move all that inside `UserStatistics`.

> "Variant"

I went with `dataSetVariant` 🤷

**Comment by ekzhang** [comment]
Hi @wenley, sorry about the delay, I've been really busy. This looks great, let me dive in more detail and test it out locally.

I might commit a couple of styling changes to put the filter selection dropdown in a slightly different location, and I'll be counting on your feedback afterward.

**Comment by ekzhang** [comment]
Let me know how you feel about this revision.

image

image

**Comment by wenley** [comment]
@ekzhang Love it - let's ship it 😎

**Pull request merged**
